version: '2'
services:
    server:
        image: webdevops/php-apache:8.0-alpine
        ports:
            - "80:80"
            - "9001:9001"
        volumes:
            - ./src:/var/www/html/src
            - ./conf/virtualhost.conf:/opt/docker/etc/httpd/vhost.conf
        links:
            - mysql
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database
        volumes:
            - ./dump:/docker-entrypoint-initdb.d

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        links:
            - mysql
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
